### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ioni90** [ioni90/furima-28192#9]
自身のフリマアプリのURL | https://furima-28192.herokuapp.com/

Basic認証のIDとパスワード |  ID:syake, PASS:shiromi
出品者用のメールアドレスとパスワード | メール：sample@sample, PASS：mino89
購入者用のメールアドレスとパスワード | メール：sample2@sample, PASS：mino90
購入用カードの番号・期限・セキュリティコード | 番号[4242424242424242], 期限[2/24], cvc[123]

**Comment by MakiTaka** [comment]
金子さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
商品購入の際、全ての項目を埋めていても商品購入ができません。
一度本番環境で確認いただき、問題ないようであれば再度ご提出をよろしくお願いいたします。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by ioni90** [comment]
レビューありがとうございます！修正いたしました！

**Comment by MakiTaka** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
